### Data Cleaning in pandas

* check for any duplicate and if any remove them
* standardize data and fix errors
* remove unwanted columns

In [1]:
import pandas as pd

In [2]:
# import dataset
pd.read_excel(r"C:\Users\klemp\Desktop\laxmi teli\ccl (1).xlsx")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [3]:
df=pd.read_excel(r"C:\Users\klemp\Desktop\laxmi teli\ccl (1).xlsx")

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [6]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [7]:
fd=df.duplicated()

In [8]:
df.iloc[20]

CustomerID                                  1020
First_Name                                Anakin
Last_Name                              Skywalker
Phone_Number                        876|678|3469
Address              910 Tatooine Road, Tatooine
Paying Customer                              Yes
Do_Not_Contact                                 N
Not_Useful_Column                           True
Name: 20, dtype: object

In [9]:
df.tail(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [10]:
df[fd]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [13]:
df.duplicated().sum()

np.int64(0)

## Step 2

In [14]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

In [15]:
df['Last_Name']

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [16]:
df['Last_Name'].str.strip()

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [17]:
df['Last_Name']=df['Last_Name'].str.strip("123._/") #reg expression to remove wanted
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [18]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [19]:
# steps to make all numbers in the phone number column to be of same lenght and format
# step1 - replace all the unwanted characters to empty string("")

In [20]:
# I want to apply the above lambda function to all the values in the phone number column
df['Phone_Number']=df['Phone_Number'].apply(lambda x:str(x))

In [21]:
  df['Phone_Number']=df['Phone_Number'].str.replace("[^0-9]","",regex=True)

In [22]:
# lambda function
l1=lambda x:x[0:3]+"-"+x[3:6]+"-"+x[6:10]
l1("1234567890")

'123-456-7890'

In [23]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [24]:
df['Phone_Number']=df['Phone_Number'].apply(l1)

In [25]:
df['Phone_Number']

0     123-545-5421
1     123-643-9775
2     706-695-0392
3     123-543-2345
4     876-678-3469
5     304-762-2467
6               --
7     876-678-3469
8               --
9     123-545-5421
10              --
11    706-695-0392
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17    706-695-0392
18              --
19    876-678-3469
Name: Phone_Number, dtype: object

In [26]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

## apply() => apply is a pandas function(series object) which will apply specified functionality to each value of a  series

In [27]:
# address
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

In [28]:
df['Address']

0                     123 Shire Lane, Shire
1                       93 West Main Street
2                        298 Drugs Driveway
3     980 Paper Avenue, Pennsylvania, 18503
4                          123 Dragons Road
5                          768 City Parkway
6                         1209 South Street
7                             98 Clue Drive
8                          123 Middle Earth
9                25th Main Street, New York
10                    612 Shire Lane, Shire
11                     2394 Hogwarts Avenue
12                         2039 Main Street
13                         343 City Parkway
14                            214 HR Avenue
15                     2395 Hogwarts Avenue
16           121 Paper Avenue, Pennsylvania
17                          3498 Super Lane
18                                      N/a
19              910 Tatooine Road, Tatooine
Name: Address, dtype: object

In [29]:
fullname="virat,kohli"
fullname.split(',')

['virat', 'kohli']

In [30]:
df['Address'].str.split(',')

0                      [123 Shire Lane,  Shire]
1                         [93 West Main Street]
2                          [298 Drugs Driveway]
3     [980 Paper Avenue,  Pennsylvania,  18503]
4                            [123 Dragons Road]
5                            [768 City Parkway]
6                           [1209 South Street]
7                               [98 Clue Drive]
8                            [123 Middle Earth]
9                 [25th Main Street,  New York]
10                     [612 Shire Lane,  Shire]
11                       [2394 Hogwarts Avenue]
12                           [2039 Main Street]
13                           [343 City Parkway]
14                              [214 HR Avenue]
15                       [2395 Hogwarts Avenue]
16            [121 Paper Avenue,  Pennsylvania]
17                            [3498 Super Lane]
18                                        [N/a]
19               [910 Tatooine Road,  Tatooine]
Name: Address, dtype: object

In [31]:
df['Address'].str.split(',',expand=True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [32]:
# spliting address into 3 sep cols
df[['Street_ Address','City','Pin_Code']]=df['Address'].str.split(',',expand=True)

In [33]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,--,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [34]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column',
       'Street_ Address', 'City', 'Pin_Code'],
      dtype='object')

In [35]:
df['Paying Customer']

0     Yes
1      No
2       N
3     Yes
4       Y
5     Yes
6      No
7       N
8     Yes
9     Yes
10    Yes
11      Y
12    Yes
13    Yes
14      N
15     No
16    Yes
17      Y
18    N/a
19    Yes
Name: Paying Customer, dtype: object

In [36]:
df['Paying Customer'].str.replace('Y','Yes')

0     Yeses
1        No
2         N
3     Yeses
4       Yes
5     Yeses
6        No
7         N
8     Yeses
9     Yeses
10    Yeses
11      Yes
12    Yeses
13    Yeses
14        N
15       No
16    Yeses
17      Yes
18      N/a
19    Yeses
Name: Paying Customer, dtype: object

In [37]:
df['Paying Customer'].str.replace('Yes','Y')

0       Y
1      No
2       N
3       Y
4       Y
5       Y
6      No
7       N
8       Y
9       Y
10      Y
11      Y
12      Y
13      Y
14      N
15     No
16      Y
17      Y
18    N/a
19      Y
Name: Paying Customer, dtype: object

In [38]:
df['Paying Customer'].str.replace('No','N')

0     Yes
1       N
2       N
3     Yes
4       Y
5     Yes
6       N
7       N
8     Yes
9     Yes
10    Yes
11      Y
12    Yes
13    Yes
14      N
15      N
16    Yes
17      Y
18    N/a
19    Yes
Name: Paying Customer, dtype: object

In [39]:
df['Paying Customer'].str.replace('N','No')

0      Yes
1      Noo
2       No
3      Yes
4        Y
5      Yes
6      Noo
7       No
8      Yes
9      Yes
10     Yes
11       Y
12     Yes
13     Yes
14      No
15     Noo
16     Yes
17       Y
18    No/a
19     Yes
Name: Paying Customer, dtype: object

In [40]:
df['Paying Customer']

0     Yes
1      No
2       N
3     Yes
4       Y
5     Yes
6      No
7       N
8     Yes
9     Yes
10    Yes
11      Y
12    Yes
13    Yes
14      N
15     No
16    Yes
17      Y
18    N/a
19    Yes
Name: Paying Customer, dtype: object

In [41]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y')
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N')

In [42]:
df['Do_Not_Contact']

0       N
1       Y
2     NaN
3       Y
4       N
5       Y
6       N
7       N
8     NaN
9       N
10      N
11    NaN
12      N
13      N
14      N
15      N
16      N
17    NaN
18      Y
19      N
Name: Do_Not_Contact, dtype: object

In [43]:
# remove columns
df.drop(columns=['Not_Useful_Column','Address'],inplace=True)

# Dealing with null values

In [44]:
df.replace('N/a','')

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,--,No,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,--,,Y,,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [45]:
df.replace('N/a','',inplace=True)
df.replace('NAN','',inplace=True)

In [46]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,--,No,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,--,,Y,,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [47]:
df.replace('N/a','',inplace=True)
df.replace('NAN','',inplace=True)

In [48]:
df.fillna('')

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,,
2,1003,Walter,White,706-695-0392,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,,
6,1007,Jeff,Winger,--,No,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,--,Yes,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,Y,,3498 Super Lane,,
18,1019,Creed,Braton,--,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,

In [49]:
df.replace('N/a','',inplace=True)
df.replace('NAN','',inplace=True)

In [50]:
df.fillna('--',inplace=True)

In [51]:
df.fillna('')

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,--
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,--,--
2,1003,Walter,White,706-695-0392,N,--,298 Drugs Driveway,--,--
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,--,--
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,--,--
6,1007,Jeff,Winger,--,No,N,1209 South Street,--,--
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,--,--
8,1009,Gandalf,--,--,Yes,--,123 Middle Earth,--,--
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,--
10,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,--
11,1012,Harry,Potter,706-695-0392,Y,--,2394 Hogwarts Avenue,--,--
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,--,--
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,--,--
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,--,--
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,--,--
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,--
17,1018,Clark,Kent,706-695-0392,Y,--,3498 Super Lane,--,--
18,1019,Creed,Braton,--,,Y,,--,--
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,--

In [52]:
df.fillna('',inplace=True)

In [53]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,--
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,--,--
2,1003,Walter,White,706-695-0392,N,--,298 Drugs Driveway,--,--
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,--,--
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,--,--
6,1007,Jeff,Winger,--,No,N,1209 South Street,--,--
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,--,--
8,1009,Gandalf,--,--,Yes,--,123 Middle Earth,--,--
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,--
10,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,--
11,1012,Harry,Potter,706-695-0392,Y,--,2394 Hogwarts Avenue,--,--
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,--,--
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,--,--
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,--,--
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,--,--
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,--
17,1018,Clark,Kent,706-695-0392,Y,--,3498 Super Lane,--,--
18,1019,Creed,Braton,--,,Y,,--,--
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,--

In [54]:
for i in df['Do_Not_Contact']:
    print(i)

N
Y
--
Y
N
Y
N
N
--
N
N
--
N
N
N
N
N
--
Y
N

In [55]:
for i in df['Do_Not_Contact']:
    if i == "Y":
        print(i)

Y
Y
Y
Y

In [56]:
for i in df.index:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [57]:
for i in df.index:
    if df.loc[i,'Do_Not_Contact']=="Y":
        df.drop(i,inplace=True)

In [58]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,--
2,1003,Walter,White,706-695-0392,N,--,298 Drugs Driveway,--,--
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,--,--
6,1007,Jeff,Winger,--,No,N,1209 South Street,--,--
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,--,--
8,1009,Gandalf,--,--,Yes,--,123 Middle Earth,--,--
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,--
10,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,--
11,1012,Harry,Potter,706-695-0392,Y,--,2394 Hogwarts Avenue,--,--
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,--,--
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,--,--
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,--,--
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,--,--
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,--
17,1018,Clark,Kent,706-695-0392,Y,--,3498 Super Lane,--,--
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,--

In [59]:
for i in df.index:
    if df.loc[i,'Do_Not_Contact']=="Y"   or   df.loc[i,'Phone_Number']==" ":
        df.drop(i,inplace=True)

In [60]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,--
2,1003,Walter,White,706-695-0392,N,--,298 Drugs Driveway,--,--
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,--,--
6,1007,Jeff,Winger,--,No,N,1209 South Street,--,--
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,--,--
8,1009,Gandalf,--,--,Yes,--,123 Middle Earth,--,--
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,--
10,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,--
11,1012,Harry,Potter,706-695-0392,Y,--,2394 Hogwarts Avenue,--,--
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,--,--
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,--,--
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,--,--
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,--,--
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,--
17,1018,Clark,Kent,706-695-0392,Y,--,3498 Super Lane,--,--
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,--

In [61]:
df.to_csv(r'C:\Users\klemp\Desktop\laxmi teli\ccl (1).xlsx.csv')

In [62]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,--
2,1003,Walter,White,706-695-0392,N,--,298 Drugs Driveway,--,--
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,--,--
6,1007,Jeff,Winger,--,No,N,1209 South Street,--,--
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,--,--
8,1009,Gandalf,--,--,Yes,--,123 Middle Earth,--,--
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,--
10,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,--
11,1012,Harry,Potter,706-695-0392,Y,--,2394 Hogwarts Avenue,--,--
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,--,--
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,--,--
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,--,--
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,--,--
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,--
17,1018,Clark,Kent,706-695-0392,Y,--,3498 Super Lane,--,--
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,--

In [63]:
df.reset_index(inplace=True,drop=True)

In [64]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,--
1,1003,Walter,White,706-695-0392,N,--,298 Drugs Driveway,--,--
2,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,--,--
3,1007,Jeff,Winger,--,No,N,1209 South Street,--,--
4,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,--,--
5,1009,Gandalf,--,--,Yes,--,123 Middle Earth,--,--
6,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,--
7,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,--
8,1012,Harry,Potter,706-695-0392,Y,--,2394 Hogwarts Avenue,--,--
9,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,--,--
10,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,--,--
11,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,--,--
12,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,--,--
13,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,--
14,1018,Clark,Kent,706-695-0392,Y,--,3498 Super Lane,--,--
15,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,--

In [65]:
df.to_csv('Datasets\ccl (1).csv',index=False)

In [66]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_ Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,--
1,1003,Walter,White,706-695-0392,N,--,298 Drugs Driveway,--,--
2,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,--,--
3,1007,Jeff,Winger,--,No,N,1209 South Street,--,--
4,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,--,--
5,1009,Gandalf,--,--,Yes,--,123 Middle Earth,--,--
6,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,--
7,1011,Samwise,Gamgee,--,Yes,N,612 Shire Lane,Shire,--
8,1012,Harry,Potter,706-695-0392,Y,--,2394 Hogwarts Avenue,--,--
9,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,--,--
10,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,--,--
11,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,--,--
12,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,--,--
13,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,--
14,1018,Clark,Kent,706-695-0392,Y,--,3498 Super Lane,--,--
15,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,--